FROM alpine:latest

# 1. Set up the environment
RUN apk update \
    && apk add --no-cache curl \
    && apk add --no-cache openjdk8-jre

# 2. Create minecraft user
RUN mkdir -p /home/minecraft /data /plugins
RUN addgroup -g 1000 minecraft \
    && adduser -h /home/minecraft -s /bin/sh -G minecraft -D -u 1000 minecraft
RUN chown minecraft:minecraft /home/minecraft /data /plugins
USER minecraft
WORKDIR /home/minecraft

# 3. Download minecraft-server
RUN curl -# -o minecraft-server.jar "https://s3.amazonaws.com/Minecraft.Download/versions/1.11.2/minecraft_server.1.11.2.jar"

# 4. Setup minecraft-server
RUN touch eula.txt \
    && echo "# Generated by docker build on `date`" >> eula.txt \
    && echo "eula=TRUE" >> eula.txt
EXPOSE 25565

# 5. Start minecraft-server
# TODO Allocate memory to the server
CMD ["java", "-jar", "minecraft-server.jar", "nogui"]
