FROM alpine:latest

# Set up the environment
RUN apk update \
    && apk add --no-cache curl \
    && apk add --no-cache openjdk8-jre

# Create minecraft user
RUN mkdir -p /home/minecraft /home/minecraft/world
RUN addgroup -g 1000 minecraft \
    && adduser -h /home/minecraft -s /bin/sh -G minecraft -D -u 1000 minecraft
RUN chown -R minecraft:minecraft /home/minecraft
USER minecraft
WORKDIR /home/minecraft

# Download minecraft-server
RUN curl -# -o minecraft-server.jar "https://s3.amazonaws.com/Minecraft.Download/versions/1.11.2/minecraft_server.1.11.2.jar"

# Setup minecraft-server
RUN touch eula.txt \
    && echo "# Generated by docker build on `date`" >> eula.txt \
    && echo "eula=TRUE" >> eula.txt
EXPOSE 25565

# Start minecraft-server
# TODO Allocate memory to the server
CMD ["java", "-jar", "minecraft-server.jar", "nogui"]
